apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-configuration
  labels:
    app: jaeger
    jaeger-infra: configuration
data:
  span-storage-type: elasticsearch
  collector: |
    collector:
      num-workers: ${COLLECTOR_NUM_WORKERS}
      queue-size: ${COLLECTOR_QUEUE_SIZE}
      zipkin:
        http-port: 9411
    es:
      server-urls: http://elasticsearch:9200
      bulk:
        size: ${ES_BULK_SIZE}
        workers: ${ES_BULK_WORKERS}
        flush-interval: ${ES_BULK_FLUSH_INTERVAL}
  query: |
    query:
      static-files: ${QUERY_STATIC_FILES}
      port: 16686
    es:
      server-urls: http://elasticsearch:9200
      bulk:
        size: ${ES_BULK_SIZE}
        workers: ${ES_BULK_WORKERS}
        flush-interval: ${ES_BULK_FLUSH_INTERVAL}

